---
# ============================================================
# GROUP VARS — Cisco ASA Hardware
# ansible_network_os moved here from all.yml so it only
# ============================================================
ansible_network_os: asa
ansible_connection: network_cli

#SSH connection parameters
ansible_user: "{{ vault_asa_user }}"
ansible_password: "{{ vault_asa_password }}"
ansible_ssh_common_args: '-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa'

#Privilege escalation parameters
ansible_become: true
ansible_become_method: ansible.netcommon.enable
ansible_become_pass: "{{ vault_asa_enable_password }}"


ansible_network_cli_ssh_type: paramiko