---
- name: 3. Platform health status
  cisco.asa.asa_command:
    commands:
      - show cpu usage
      - show memory
      - show processes cpu-usage non-zero sorted
  register: asa_platform_health
  
- name: Debug platform health
  debug:
    var: asa_platform_health.stdout