---
- name: "4. CPU top processes"
  cisco.asa.asa_command:
    commands:
      - show processes cpu-usage non-zero sorted
  register: asa_cpu_top

- name: "DEBUG | CPU top processes raw"
  ansible.builtin.debug:
    var: asa_cpu_top.stdout

- name: "SET | CPU top processes string (first 20 lines)"
  ansible.builtin.set_fact:
    asa_cpu_top_str: >-
      {{ (asa_cpu_top.stdout[0] | regex_replace('\\r', '')).split('\n')[0:20] | join('\n') }}