---
- name: 8. Transceiver diagnostics equivalent
  cisco.asa.asa_command:
    commands:
      - show inventory
      - show interface
  register: asa_transceiver
  
- name: Debug transceiver diagnostics
  debug:
    var: asa_transceiver.stdout