---
- name: 9. Topology and neighbor data
  cisco.asa.asa_command:
    commands:
      - show arp
      - show route
  register: asa_topology
  
- name: Debug topology and neighbor data
  debug:
    var: asa_topology.stdout