---
- name: 10. Routing and neighbor state
  cisco.asa.asa_command:
    commands:
      - show ospf neighbor
      - show route
  register: asa_routing
  
- name: Debug routing and neighbor state
  debug:
    var: asa_routing.stdout